name: Playwright Tests & Deploy Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean previous Allure reports
        run: rm -rf allure-report  # Clean the previous Allure reports

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Playwright Tests in Docker
        run: |
          docker build -t playwright-tests .
          docker run --rm -v $PWD/allure-results:/app/allure-results playwright-tests

      - name: Install Dependencies (Required for Allure Report)
        run: npm ci

      - name: Generate Allure Report
        run: |
          npm run allure:generate
          mkdir -p docs  # Ensure the docs folder exists
          mv allure-report/* docs/  # Move only the contents of allure-report

      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update Allure Report" || echo "No changes to commit"
          git push origin main

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs  # Corrected publish directory
