name: Playwright Tests & Deploy Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean previous Allure reports
        run: |
          rm -rf allure-report
          rm -rf allure-results
          rm -rf docs/*  # Cleans the docs folder (be sure no important files are in it)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Playwright Tests in Docker
        run: |
          docker build -t playwright-tests .
          docker run --rm -v $PWD/allure-results:/app/allure-results playwright-tests

      - name: Install Dependencies (Required for Allure Report)
        run: npm ci

      - name: Generate Allure Report
        run: |
          npm run allure:generate
          # Check if the allure-report folder is generated and has contents
          ls allure-report || echo "Allure report not generated!"
          mkdir -p docs  # Ensure the docs folder exists
          mv allure-report/* docs/  # Move only the contents of allure-report

      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update Allure Report" || echo "No changes to commit"
          git push origin main

  upload_to_s3:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Upload Allure Report to S3
        run: |
          aws s3 cp docs/ s3://testreportallure/ --recursive --region us-east-1

  notify:
    needs: upload_to_s3
    runs-on: ubuntu-latest

    steps:
      - name: Send Allure Report URL to Slack
        run: |
          S3_URL="https://s3.eu-north-1.amazonaws.com/testreportallure/index.html"
          curl -X POST -H 'Content-type: application/json' --data '{
          "text": "The latest Allure Report is available at: '"${S3_URL}"'"
           }' ${{ secrets.SLACK_WEBHOOK_URL }}
